sudo: required

language: generic

services:
  - docker

script:
  - docker run --rm -it -v $(pwd):/data woodjme/tex xelatex cv.tex

before_deploy:
  - find . ! -name 'cv.pdf' -type f -exec rm -f {} +
  - echo 'cv.jamiewood.io' > CNAME
  - echo '<html><script>window.location.href="https://cv.jamiewood.io/cv.pdf"</script></html>' > index.html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
