sudo: required

language: generic

services:
  - docker

script:
  - docker run --rm -it -v $(pwd):/data woodjme/tex xelatex cv.tex

before_deploy:
  - find . ! -name 'cv.pdf' ! -name 'CNAME' -type f -exec rm -f {} +

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
